spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:suwei1979/config-repo.git
          uri: git@github.com:suwei1979/${PRODUCT_NAME:config-server}.git
          search-paths: '{profile}/{application}'

#          uri: http://git.intra.weibo.com/jinsong6/spring-cloud.git
#          searchPaths: '{application}'
#          username: jinsong6
#          password: Zhujinsong1994

server:
  port: 8881
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  security:
    enabled: false